// <auto-generated />
using IncomeTaxCalculator.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalculator.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaxCalculatorDbContext))]
    partial class TaxCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("IncomeTaxCalculator.Server.Domain.Entities.TaxBracket", b =>
                {
                    b.Property<string>("TaxSystem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RatePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UpperLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TaxSystem", "BandName");

                    b.HasIndex("TaxSystem")
                        .HasDatabaseName("IX_TaxBrackets_TaxSystem");

                    b.HasIndex("TaxSystem", "LowerLimit")
                        .HasDatabaseName("IX_TaxBrackets_TaxSystem_LowerLimit");

                    b.ToTable("TaxBrackets", (string)null);

                    b.HasData(
                        new
                        {
                            TaxSystem = "UK",
                            BandName = "Tax Band A",
                            LowerLimit = 0m,
                            RatePercentage = 0,
                            UpperLimit = 5000m
                        },
                        new
                        {
                            TaxSystem = "UK",
                            BandName = "Tax Band B",
                            LowerLimit = 5000m,
                            RatePercentage = 20,
                            UpperLimit = 20000m
                        },
                        new
                        {
                            TaxSystem = "UK",
                            BandName = "Tax Band C",
                            LowerLimit = 20000m,
                            RatePercentage = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
